NetworkPkg: Remove unused variable
XCODE5 toolchain finds this, with error:
WifiConnectionMgrHiiConfigAccess.c:393:29: error: variable 'AvailableCount' set but not used

Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>