CryptoPkg/CryptX509.c: Remove unused variable
Without this change, build fails on current XCODE5, and we see:

/Users/mjsbeaton/OpenSource/edk2/CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c:105:12: error: variable 'Index' set but not used [-Werror,-Wunused-but-set-variable]
  UINTN    Index;
           ^

Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>