SecurityPkg: Remove unused variables
XCODE5 toolchain finds this, with error:
Tpm2Capability.c:535:23: error: variable 'ActivePcrBankCount' set but not used

Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>