SecurityPkg: Update libspdm to 3.7.0
https://github.com/DMTF/libspdm/commit/0f6c6a3e800f487242b973b5858c534186a7db05
fixes incorrectly typed return values in libspdm_hmac_new.

Without this commit XCODE5 refuses to build SecurityPkg, with multiple
errors corresponding to the lines fixed above, each of the form:

libspdm_crypt_hmac.c:31:16: error: expression which evaluates to zero treated as a null pointer constant of type 'void *'

I have updated libspdm to the minimum whole build number which includes
the required commit, though higher releases than 3.7.0, up to 3.8.1, are
available.

Signed-off-by: Mike Beaton <mjsbeaton@gmail.com>